<?php

/**
 * @file
 * Hooks and callbacks for this module.
 *
 * This file is part of the Islandora EAD Solution Pack.
 * Copyright (C) 2015  Drexel University.
 *
 * The Islandora EAD Solution Pack is free software; you can redistribute
 * it and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * The Islandora EAD Solution Pack is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with The Islandora EAD Solution Pack; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

/**
 * Implements hook_menu().
 */
function islandora_ead_menu() {
  $items = array();

  $items['islandora/ead/lookup'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'EAD Lookup by ID',
    'file' => 'includes/utilities.inc',
    'page callback' => 'islandora_ead_id_lookup',
    'access arguments' => array(ISLANDORA_VIEW_OBJECTS),
  );

  $items['islandora/object/%islandora_object/manage/ead'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'EAD',
    'file' => 'includes/manage.form.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_ead_manage_form', 2),
    'access callback' => 'islandora_ead_manage_access_callback',
    'access arguments' => array(2),
  );

  $items['islandora/object/%islandora_object/manage/ead/%'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Create Association',
    'file' => 'includes/association_upload.form.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_ead_association_upload_form', 2, 5),
    'access callback' => 'islandora_ead_manage_access_callback',
    'access arguments' => array(2),
  );

  $items['islandora/object/%islandora_object/manage/ead/%/modify'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Modify Association',
    'file' => 'includes/association_modify.form.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_ead_association_modify_form', 2, 5),
    'access callback' => 'islandora_ead_manage_access_callback',
    'access arguments' => array(2),
  );

  $items['islandora_ead_object/autocomplete/object'] = array(
    'page callback' => 'islandora_ead_object_autocomplete',
    'page arguments' => array(3),
    'access arguments' => array('administer compound relationships'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}
/**
 * Implements hook_theme().
 */
function islandora_ead_theme() {
  return array(
    'islandora_ead' => array(
      'arguments' => array('object' => NULL),
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-ead',
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_ead_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_ead');
  $datastreams_path = "$module_path/xml";

  // EAD Content Model.
  $ead_content_model = $connection->repository->constructObject('islandora:eadCModel');
  $ead_content_model->owner = 'fedoraAdmin';
  $ead_content_model->label = 'Islandora EAD Content Model';
  $ead_content_model->models = 'fedora-system:ContentModel-3.0';

  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $ead_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$datastreams_path/islandora_eadCModel_ds_composite_model.xml", FALSE);
  $ead_content_model->ingestDatastream($datastream);

  return array(
    'islandora_ead' => array(
      'title' => 'Islandora EAD Content Model',
      'objects' => array($ead_content_model),
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_ead_islandora_eadcmodel_islandora_ingest_steps() {
  return array(
    'islandora_ead' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_ead_upload_form',
      'module' => 'islandora_ead',
      'file' => 'includes/ead_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ead_islandora_eadcmodel_islandora_view_object($object) {
  $output = theme('islandora_ead', array('object' => $object));
  return array('islandora_ead' => $output);
}

/**
 * Callback to limit access to EAD management interfaces.
 */
function islandora_ead_manage_access_callback($object) {
  $permissions = array(
    ISLANDORA_ADD_DS,
    ISLANDORA_METADATA_EDIT,
    ISLANDORA_PURGE,
  );

  $content_models = array('islandora:eadCModel');

  return islandora_user_access($object, $permissions, $content_models);
}

/**
 * Implements hook_islandora_solr_object_result_alter().
 */
function islandora_ead_islandora_solr_object_result_alter(&$search_result, $query_processor) {
  if (array_key_exists('ispartof_display', $search_result['solr_doc'])) {
    $ead_pid = $search_result['solr_doc']['ispartof_pid'];
    $ead_title = $search_result['solr_doc']['ispartof_display'];
    $search_result['solr_doc']['ispartof_display'] = l($ead_title, "islandora/object/$ead_pid");
  }
}

/**
 * Autocomplete callback for object search.
 *
 * @param string $string
 *   The user supplied string that is being searched for.
 */
function islandora_compound_ead_autocomplete($string) {
  $matches = array();
  $islandora_tuque = islandora_get_tuque_connection();
  /*$compound_enforcement = variable_get('islandora_compound_object_compound_children', TRUE);*/

  // Build escapes as per:
  // - https://www.w3.org/TR/xmlschema-2/#dt-metac and
  // - https://www.w3.org/TR/xmlschema-2/#dt-cces1
  $meta = array(
    '\\',
    '.',
    '?',
    '*',
    '+',
    '{',
    '}',
    '(',
    ')',
    '[',
    ']',
    '|',
    '-',
    '^',
  );
  $escape_meta = function ($meta) {
    return "\\\\$meta";
  };
  $meta_replacements = drupal_map_assoc($meta, $escape_meta);

  $replacements = array(
    '!compound_model' => '?model',
    '!text' => str_replace(array_keys($meta_replacements), $meta_replacements, $string),
  );
  /*if ($compound_enforcement && $parent) {
    $compound_model = ISLANDORA_COMPOUND_OBJECT_CMODEL;
    $replacements['!compound_model'] = "<info:fedora/$compound_model>";
  }*/

  $query = <<<'EOQ'
SELECT DISTINCT ?pid ?title
FROM <#ri>
WHERE {
  ?pid <fedora-model:label> ?title .
  FILTER(regex(?title, "!text", 'i') || regex(str(?pid), "!text", 'i'))
}
LIMIT 10
EOQ;
  $query = format_string($query, $replacements);
  $results = $islandora_tuque->repository->ri->sparqlQuery($query, 'unlimited');

  foreach ($results as $result) {
    $matches[$result['pid']['value']] = t('!title (!pid)', array(
      '!title' => $result['title']['value'],
      '!pid' => $result['pid']['value'],
    ));
  }
  drupal_json_output($matches);
}
